apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: comosyme
  name: consul-config
spec:
  storageClassName: edgex-consul-config-volume
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
status: {}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: comosyme
  name: consul-data
spec:
  storageClassName: edgex-consul-data-volume
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
status: {}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: comosyme
  name: db-data
spec:
  storageClassName: edgex-db-volume
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
status: {}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: comosyme
  name: log-data
spec:
  storageClassName: edgex-support-logging-volume
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
status: {}