apiVersion: v1
kind: Service
metadata:
  namespace: comosyme
  labels:
    org.edgexfoundry.service: {{.Values.edgex.app.device.gpio}}
  name: {{.Values.edgex.app.device.gpio}}
spec:
  ports:
  - name: "60000"
    port: 60000
    targetPort: 60000
    nodePort: {{.Values.expose.nodePort.device.gpio}}
  selector:
    org.edgexfoundry.service: {{.Values.edgex.app.device.gpio}}
  type: {{.Values.expose.type}}
status:
  loadBalancer: {}