apiVersion: v1
kind: Service
metadata:
  namespace: comosyme
  labels:
    org.edgexfoundry.service: {{.Values.edgex.app.core.data}}
  name: {{.Values.edgex.app.core.data}}
spec:
  ports:
  - name: "59880"
    port: 59880
    targetPort: 59880
    nodePort: {{.Values.expose.nodePort.core.data}}
  - name: "5563"
    port: 5563
    targetPort: 5563
  - name: "5564"
    port: 5564
    targetPort: 5564
  selector:
    org.edgexfoundry.service: {{.Values.edgex.app.core.data}}
  type: {{.Values.expose.type}}
status:
  loadBalancer: {}
