apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: comosyme
  labels:
    org.edgexfoundry.service: {{.Values.edgex.app.application.servicegpio}}
  name: {{.Values.edgex.app.application.servicegpio}}
spec:
  replicas: {{.Values.edgex.replicas.application.servicegpio}}
  selector:
    matchLabels:
      org.edgexfoundry.service: {{.Values.edgex.app.application.servicegpio}}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        org.edgexfoundry.service: {{.Values.edgex.app.application.servicegpio}}
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: {{.Values.edgex.app.application.servicegpio}}
        {{- if eq .Values.architecture "arm64" }}
        image: {{.Values.edgex.image.application.servicegpio.arm64.repository}}:{{.Values.edgex.image.application.servicegpio.arm64.tag}}
        {{- else }}
        image: {{.Values.edgex.image.application.servicegpio.amd64.repository}}:{{.Values.edgex.image.application.servicegpio.amd64.tag}}
        {{- end }}
        imagePullPolicy: {{.Values.edgex.image.application.servicegpio.pullPolicy}}
        command: ["/app-gpio-mqtt-telegraf"]
        args: ["-cp=consul.http://edgex-core-consul:8500", "--registry", "--confdir=/res"]
        envFrom:
        - configMapRef:
            name: edgex-common-variables
        env:
        - name: SERVICE_HOST
          value: {{.Values.edgex.app.application.servicegpio}}
        ports:
        - containerPort: {{.Values.expose.nodePort.application.servicegpio}}
        volumeMounts:
        - name: zoneinfo
          mountPath: /etc/localtime
          subPath: CET
          readOnly: true
        - name: persistencepath
          mountPath: /sensors_data/
        - name: cpuinfo
          mountPath: /proc/
        readinessProbe:
          httpGet:
            path: /api/v2/ping
            port: 59782
          initialDelaySeconds: 5
          periodSeconds: 15
          successThreshold: 1
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /api/v2/ping
            port: 59782
          initialDelaySeconds: 5
          periodSeconds: 15
          successThreshold: 1
          failureThreshold: 3
      {{- if .Values.edgex.resources.application.servicegpio.enforceLimits }}
        resources:
          limits:
            memory: {{ .Values.edgex.resources.application.servicegpio.limits.memory }}
            cpu: {{ .Values.edgex.resources.application.servicegpio.limits.cpu }}
          requests:
            memory: {{ .Values.edgex.resources.application.servicegpio.requests.memory }}
            cpu: {{ .Values.edgex.resources.application.servicegpio.requests.cpu }}
      {{- end}}
      hostname: {{.Values.edgex.app.application.servicegpio}}
      restartPolicy: Always
      volumes:
        - name: zoneinfo
          hostPath:
            path: /usr/share/zoneinfo
        - name: persistencepath
          hostPath:
            path: /home/pi/sensors_data/
        - name: cpuinfo
          hostPath:
            path: /proc/
status: {}