{
 "title": "HSC Prototype1",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "samplingTime", "query": "1ms, 1s, 1m, 1h" },
   {
    "name": "Frequency_index",
    "query": "import \"influxdata/influxdb/schema\"\r\n\r\nschema.measurementFieldKeys(\r\n    bucket: \"OilMonitoringData\",\r\n    measurement: \"1000000033fec2d1\",\r\n)\r\n\r\n"
   }
  ]
 },
 "panels": [
  {
   "title": "Concentration TimeSeries",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET",
     "query": "from(bucket: \"OilMonitoringData\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"1000000033fec2d1\")\r\n  |> filter(fn: (r) => r[\"sensor_name\"] == \"concentration\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Frequence_${Frequency_index}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    },
    {
     "query": "from(bucket: \"OilMonitoringData\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"1000000033fec2d1\")\r\n  |> filter(fn: (r) => r[\"sensor_name\"] == \"concentration\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Impedance_${Frequency_index}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    },
    {
     "query": "from(bucket: \"OilMonitoringData\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"1000000033fec2d1\")\r\n  |> filter(fn: (r) => r[\"sensor_name\"] == \"concentration\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Phase_${Frequency_index}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    },
    {
     "query": "from(bucket: \"OilMonitoringData\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"1000000033fec2d1\")\r\n  |> filter(fn: (r) => r[\"sensor_name\"] == \"concentration\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Temperature\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Pump TimeSeries",
   "type": "timeseries",
   "gridPos": { "h": 19, "w": 17, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET",
     "query": "from(bucket: \"OilMonitoringData\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"1000000033fec2d1\")\r\n  |> filter(fn: (r) => r[\"sensor_name\"] == \"pump_gpio\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"State\")\r\n  |> filter(fn: (r) => r[\"topic\"] == \"Data/1000000033fec2d1/pump_gpio\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 15 },
   "options": {
    "content": "<img src=https://d11wkw82a69pyn.cloudfront.net/siteassets/images/xma_dindi/concept_reply.png />"
   },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 22 },
   "options": {
    "content": "<img src=https://thertoinnovationsummit.eu/sites/default/files/2020-02/RISE_Logo_mText_Black.png />"
   },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET"
    }
   ]
  },
  {
   "title": "CSV download",
   "type": "gapit-htmlgraphics-panel",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 30 },
   "options": {
    "reduceOptions": {
     "calcs": [
      "lastNotNull",
      "last",
      "first",
      "firstNotNull",
      "min",
      "max",
      "mean",
      "sum",
      "count",
      "range",
      "delta",
      "step",
      "diff",
      "logmin",
      "allIsZero",
      "allIsNull",
      "diffperc"
     ]
    }
   },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET",
     "query": "pH = from(bucket: \"hydraulic-smart-controller\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"PH\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Temperature\" or r[\"_field\"] == \"PhValue\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> drop(columns: [\"sensor\"])\r\n  |> rename(columns: {Temperature: \"Temperature_pH\"})\r\n\r\ndensity = from(bucket: \"hydraulic-smart-controller\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"DENSITY\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Density\" or r[\"_field\"] == \"DynamicViscosity\" or r[\"_field\"] == \"Temperature\")\r\n  |> filter(fn: (r) => r[\"sensor\"] == \"DENSITY\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({\r\n    r with kinematicViscosity: (r.DynamicViscosity/r.Density)*1000.0\r\n  }))\r\n  |> drop(columns: [\"DynamicViscosity\", \"sensor\"])\r\n  |> rename(columns: {Temperature: \"Temperature_density\"})\r\n\r\nconductivity = from(bucket: \"hydraulic-smart-controller\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"CONDUCTIVITY\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Salinity\" or r[\"_field\"] == \"Tds\" or r[\"_field\"] == \"Temperature\" or r[\"_field\"] == \"ElectricalConductivity\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> drop(columns: [\"sensor\"])\r\n  |> rename(columns: {Temperature: \"Temperature_conductivity\"})\r\n\r\nTempRelH = from(bucket: \"hydraulic-smart-controller\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"T9501\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Temperature\" or r[\"_field\"] == \"RelativeHumidity\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> drop(columns: [\"sensor\"])\r\n  |> rename(columns: {Temperature: \"Temperature_T9501\"})\r\n\r\npH_desnity_join = join (\r\n    tables: {pH: pH, density: density},\r\n    on: [\"_time\", \"_stop\", \"_start\"]\r\n)\r\n\r\nconductivity_join = join (\r\n    tables: {pH_desnity_join: pH_desnity_join, conductivity: conductivity},\r\n    on: [\"_time\", \"_stop\", \"_start\"]\r\n)\r\n\r\njoin (\r\n    tables: {conductivity_join: conductivity_join, TempRelH: TempRelH},\r\n    on: [\"_time\", \"_stop\", \"_start\"]\r\n)\r\n  |> drop(columns: [\"_measurement_pH\", \"_measurement_density\", \"_measurement_conductivity_join\", \"_measurement_TempRelH\"])\r\n  |> map(fn: (r) =>\r\n  { \r\n    return {\r\n      start: v.timeRangeStart,\r\n      stop: v.timeRangeStop\r\n    }\r\n  })"
    }
   ]
  },
  {
   "title": "PH Sensor TimeSeries",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET",
     "query": "from(bucket: \"OilMonitoringData\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"1000000033fec2d1\")\r\n  |> filter(fn: (r) => r[\"sensor_name\"] == \"pH\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"PhValue\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    },
    {
     "query": "from(bucket: \"OilMonitoringData\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"1000000033fec2d1\")\r\n  |> filter(fn: (r) => r[\"sensor_name\"] == \"pH\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Temperature\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Conductivity Sensors TimeSeries",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 50 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET",
     "query": "from(bucket: \"OilMonitoringData\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"1000000033fec2d1\")\r\n  |> filter(fn: (r) => r[\"sensor_name\"] == \"conductivity\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"ElectricalConductivity\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    },
    {
     "query": "from(bucket: \"OilMonitoringData\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"1000000033fec2d1\")\r\n  |> filter(fn: (r) => r[\"sensor_name\"] == \"conductivity\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Salinity\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    },
    {
     "query": "from(bucket: \"OilMonitoringData\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"1000000033fec2d1\")\r\n  |> filter(fn: (r) => r[\"sensor_name\"] == \"conductivity\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Tds\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    },
    {
     "query": "from(bucket: \"OilMonitoringData\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"1000000033fec2d1\")\r\n  |> filter(fn: (r) => r[\"sensor_name\"] == \"conductivity\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Temperature\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Temperatures Last Readings",
   "type": "gauge",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET",
     "query": "from(bucket: \"OilMonitoringData\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"1000000033fec2d1\")\r\n  |> filter(fn: (r) => r[\"sensor_name\"] == \"conductivity\" or r[\"sensor_name\"] == \"concentration\" or r[\"sensor_name\"] == \"pH\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Temperature\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "PH Last Reading",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 81 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET",
     "query": "from(bucket: \"OilMonitoringData\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"1000000033fec2d1\")\r\n  |> filter(fn: (r) => r[\"sensor_name\"] == \"pH\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"PhValue\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "EC Last Reading",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "us/cm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET",
     "query": "from(bucket: \"OilMonitoringData\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"1000000033fec2d1\")\r\n  |> filter(fn: (r) => r[\"sensor_name\"] == \"conductivity\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"ElectricalConductivity\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Salinity Last Reading",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "mg/L" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET",
     "query": "from(bucket: \"OilMonitoringData\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"1000000033fec2d1\")\r\n  |> filter(fn: (r) => r[\"sensor_name\"] == \"conductivity\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Salinity\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "TDS Last Reading",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "mg/L" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET",
     "query": "from(bucket: \"OilMonitoringData\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"1000000033fec2d1\")\r\n  |> filter(fn: (r) => r[\"sensor_name\"] == \"conductivity\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Tds\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "PH Sensor Calibration parameters",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 92 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET",
     "query": "from(bucket: \"OilMonitoringData\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"1000000033fec2d1\")\r\n  |> filter(fn: (r) => r[\"sensor_name\"] == \"pH\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"PhCalibrationRawAd\" or r[\"_field\"] == \"PhCalibrationRawAd0\" or r[\"_field\"] == \"PhCalibrationRawAd1\" or r[\"_field\"] == \"PhCalibrationRawAd2\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Conductivity Sensor Calibration parameters",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 92 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET",
     "query": "from(bucket: \"OilMonitoringData\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"1000000033fec2d1\")\r\n  |> filter(fn: (r) => r[\"sensor_name\"] == \"conductivity\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"EcRawAd\" or r[\"_field\"] == \"EcTempCoff\" or r[\"_field\"] == \"SalinityCoff\" or r[\"_field\"] == \"TdsCoff\" or r[\"_field\"] == \"ElectrodeConst\" or r[\"_field\"] == \"EcCalib_1413\" or r[\"_field\"] == \"EcCalib_12880\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  }
 ]
}