[Writable]
LogLevel = 'INFO'
  [Writable.InsecureSecrets]
    [Writable.InsecureSecrets.DB]
    path = "redisdb"
      [Writable.InsecureSecrets.DB.Secrets]
      username = ""
      password = ""

[Service]
HealthCheckInterval = "10s"
Host = "concentration-application-service"
Port = 59784 # Adjust if running multiple examples at the same time to avoid duplicate port conflicts
ServerBindAddr = "" # if blank, uses default Go behavior https://golang.org/pkg/net/#Listen
StartupMsg = 'This is a sample Application Service which filters, custom converts, prints and publishes back to message bus'
RequestTimeout = "30s"
MaxRequestSize = 0
MaxResultCount = 0

[Registry]
Host = 'edgex-core-consul'
Port = 8500
Type = 'consul'

[Clients]
  [Clients.core-metadata]
  Protocol = "http"
  Host = "edgex-core-metadata"
  Port = 59881

  [Clients.core-data]
  Protocol = "http"
  Host = "edgex-core-data"
  Port = 59880

[Trigger]
Type="edgex-messagebus"
  [Trigger.EdgexMessageBus]
  Type = "redis"
    [Trigger.EdgexMessageBus.SubscribeHost]
    Host = "edgex-redis"
    Port = 6379
    Protocol = "redis"
    SubscribeTopics="edgex/events/#"


[ApplicationSettings]
DeviceNames = "ConcentrationSensorDevice"
