apiVersion: v1
kind: Service
metadata:
  namespace: comosyme
  labels:
    org.edgexfoundry.service: {{.Values.edgex.app.db.redis}}
  name: {{.Values.edgex.app.db.redis}}
spec:
  ports:
  - name: "6379"
    port: 6379
    targetPort: 6379
    nodePort: {{.Values.expose.nodePort.db.redis}}   #???
  selector:
    org.edgexfoundry.service: {{.Values.edgex.app.db.redis}}
  type: {{.Values.expose.type}}
status:
  loadBalancer: {}
