apiVersion: v1
kind: Service
metadata:
  namespace: comosyme
  labels:
    org.edgexfoundry.service: {{.Values.edgex.app.rules.engine}}
  name: {{.Values.edgex.app.rules.engine}}
spec:
  ports:
  - name: "59701"
    port: 59701
    targetPort: 59701
    nodePort: {{.Values.expose.nodePort.rules.engine}}
  selector:
    org.edgexfoundry.service: {{.Values.edgex.app.rules.engine}}
  type: {{.Values.expose.type}}
status:
  loadBalancer: {}
