apiVersion: v1
kind: Service
metadata:
  namespace: comosyme
  labels:
    org.edgexfoundry.service: {{.Values.edgex.app.application.servicet9501}}
  name: {{.Values.edgex.app.application.servicet9501}}
spec:
  ports:
  - name: "59781"
    port: 59781
    targetPort: 59781
    nodePort: {{.Values.expose.nodePort.application.servicet9501}}
  selector:
    org.edgexfoundry.service: {{.Values.edgex.app.application.servicet9501}}
  type: {{.Values.expose.type}}
status:
  loadBalancer: {}
