apiVersion: v1
kind: Service
metadata:
  namespace: comosyme
  labels:
    org.edgexfoundry.service: {{.Values.edgex.app.device.mqtt}}
  name: {{.Values.edgex.app.device.mqtt}}
spec:
  ports:
  - name: "59998"
    port: 59998
    targetPort: 59998
    nodePort: {{.Values.expose.nodePort.device.mqtt}}
  selector:
    org.edgexfoundry.service: {{.Values.edgex.app.device.mqtt}}
  type: {{.Values.expose.type}}
status:
  loadBalancer: {}